export const wallet = [
  { image: "/images/trust.jpg", title: "Trust Wallet" },
  { image: "/images/metamask.jpg", title: "Metamask" },
  { image: "/images/avalanche.png", title: "Avalanche" },
  { image: "/images/wallet.png", title: "Wallet Connect" },
  { image: "/images/coinomi.jpg", title: "Coinomi" },
  { image: "/images/gnosis.jpg", title: "Gnosis Safe Multisig" },
  { image: "/images/solana.png", title: "Solana" },
  { image: "/images/halo.jpg", title: "HaloDefi Wallet" },
  { image: "/images/keplr.jpg", title: "Keplr" },
  { image: "/images/argent.jpg", title: "Argent" },
  { image: "/images/coinbase.png", title: "Coinbase" },
  { image: "/images/tenset.jpg", title: "Tenset" },
  { image: "/images/block.png", title: "Block Wallet" },
  { image: "/images/atomic.jpg", title: "Atomic" },
  { image: "/images/rainbow.jpg", title: "Rainbow" },
  { image: "/images/03.jpg", title: "03Wallet" },
  { image: "/images/1inch.jpg", title: "1inch Wallet" },
  { image: "/images/aktion.jpg", title: "AKTIONARIAT" },
  { image: "/images/alice.jpg", title: "Alice" },
  { image: "/images/alpha.jpg", title: "AlphaWallet" },
  { image: "/images/crypto.jpg", title: "Crypto | Defi" },
  { image: "/images/enjin.jpg", title: "Enjin" },
  { image: "/images/at.jpg", title: "AT.Wallet" },
  { image: "/images/atoken.jpg", title: "AToken Wallet" },
  { image: "/images/polygon.jpg", title: "Polygon" },
  { image: "/images/authereum.jpg", title: "Autheruem" },
  { image: "/images/binance.jpg", title: "Binance Smart Chain" },
  { image: "/images/bitkeep.jpg", title: "Bitkeep " },
  { image: "/images/bitpay.jpg", title: "Bitpay" },
  { image: "/images/brige.jpg", title: "Brige Wallet" },
  { image: "/images/coin98.jpg", title: "Coin98" },
  { image: "/images/cool.jpg", title: "CoolWallets" },
  { image: "/images/cybavo.jpg", title: "CYBAVO Wallet" },
  { image: "/images/dcent.jpg", title: "D'CENT" },
  { image: "/images/defiant.jpg", title: "Defiant" },
  { image: "/images/dharma.jpg", title: "Dharma" },
  { image: "/images/dok.jpg", title: "Dok Wallet" },
  { image: "/images/easy.jpg", title: "EasyPocket" },
  { image: "/images/eidoo.jpg", title: "Eidoo" },
  { image: "/images/ellipal.jpg", title: "Ellipal" },
  { image: "/images/equal.jpg", title: "Equal" },
  { image: "/images/flare.jpg", title: "Flare Wallet" },
  { image: "/images/grid.jpg", title: "GridPlus" },
  { image: "/images/guard.jpg", title: "Guarda Wallet" },
  { image: "/images/halodefi.jpg", title: "HaloDefi" },
  { image: "/images/hask.jpg", title: "HaskKey Me" },
  { image: "/images/huobi.jpg", title: "Huobi Wallet" },
  { image: "/images/imtoken.jpg", title: "imToken" },
  { image: "/images/infinito.jpg", title: "infinito" },
  { image: "/images/infinity.jpg", title: "Infinity Wallet" },
  { image: "/images/jade.jpg", title: "Jade Wallet" },
  { image: "/images/keyring.jpg", title: "KEYRING PRO" },
  { image: "/images/kyberswap.jpg", title: "KyberSwap" },
  { image: "/images/ledger.jpg", title: "Ledger Live" },
  { image: "/images/loop.jpg", title: "Loopring Wallet" },
  { image: "/images/math.jpg", title: "MathWallet" },
  { image: "/images/midas.jpg", title: "Midas" },
  { image: "/images/morix.jpg", title: "MoriX" },
  { image: "/images/mykey.jpg", title: "MYKEY" },
  { image: "/images/nash.jpg", title: "Nash" },
  { image: "/images/onto.jpg", title: "ONTO" },
  { image: "/images/ownbit.jpg", title: "Ownbit" },
  { image: "/images/pillar.jpg", title: "pillar" },
  { image: "/images/peak.jpg", title: "PEAKDEFI Wallet" },
  { image: "/images/phantom.jpg", title: "Phantom" },
  { image: "/images/plasma.jpg", title: "PlasmaPay" },
  { image: "/images/rwallet.jpg", title: "RWallet" },
  { image: "/images/safepal.jpg", title: "SafePal" },
  { image: "/images/spart.jpg", title: "SpartPoint" },
  { image: "/images/spatium.jpg", title: "Spatium" },
  { image: "/images/talken.jpg", title: "Talken Wallet" },
  { image: "/images/tokenary.jpg", title: "Tokenary" },
  { image: "/images/tokenpocket.jpg", title: "TokenPocket" },
  { image: "/images/tongue.jpg", title: "Tongue Wallet" },
  { image: "/images/torus.jpg", title: "Torus" },
  { image: "/images/trustvault.jpg", title: "Trust Vault" },
  { image: "/images/trustee.jpg", title: "Trustee Wallet" },
  { image: "/images/Unstoppable.jpg", title: "Unstoppable Wallet" },
  { image: "/images/viawallet.jpg", title: "Viawallet" },
  { image: "/images/vision.jpg", title: "Vision" },
  { image: "/images/walletio.jpg", title: "Wallet.io" },
  { image: "/images/xinfin.jpg", title: "XinFin XDC Network" },
  { image: "/images/zelcore.jpg", title: "Zelcore" },
];
